[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = [".", "common", "flask"]
addopts = "-v"

[tool.coverage.run]
relative_files = true
source = ["."]
include = [
    "common/models/*",
    "common/repositories/*",
    "common/services/*",
    "common/utils/*",
    "common/helpers/*",
    "flask/app/helpers/*"
]

[tool.coverage.xml]
output = "coverage.xml"
